<header>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">

    <div class="d-flex flex-column flex-md-row align-items-center pb-3 text-white mb-4 bg-dark border-bottom">
        <a href="/main" class="d-flex align-items-center text-white link-body-emphasis text-decoration-none">
            <span class="fs-4">Главная</span>
        </a>

        <nav class="d-inline-flex text-white mt-2 mt-md-0 ms-md-auto">
            <a class="me-3 py-2 text-white link-body-emphasis text-decoration-none" href="/product">Продукты</a>
            <a class="me-3 py-2 text-white link-body-emphasis text-decoration-none" href="/reviews">Отзывы</a>
            <a class="me-3 py-2 text-white link-body-emphasis text-decoration-none" href="/shoppingCart">Корзина</a>
            <a class="py-2 link-body-emphasis text-white text-decoration-none" href="/logout">Выйти</a>
        </nav>
    </div>

</header>

<body class="bg-dark" text="white">
<div class="container">
    {content}
</div>

</body>

<footer class="pt-4 my-md-5 pt-md-5 border-top ">
    <div class="row">
        <div class="col-12 col-md">
            <small class="d-block mb-3 text-white">© 2017–2023</small>
        </div>
        <div class="col-6 col-md text-white">
            <h5  >Features</h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
            </ul>
        </div>
        <div class="col-6 col-md text-white">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
            </ul>
        </div>
        <div class="col-6 col-md text-white">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
            </ul>
        </div>
    </div>
</footer>